"""Jarvis auto-start installer.

Creates launchd plist (macOS), a Task Scheduler entry or startup script
(Windows), or a systemd user service (Linux) for automatic startup on
login. The installer also persists startup defaults such as the project
directory, browser URLs, Warp/Claude settings, and microphone behavior.
"""

from __future__ import annotations

import os
import platform
import plistlib
import shlex
import subprocess
import sys
from dataclasses import fields
from pathlib import Path
from typing import Any

from jarvis.shared.config import JarvisConfig

PLIST_LABEL = "com.jarvis.agent"
WINDOWS_TASK_NAME = "JarvisAI"
WINDOWS_STARTUP_NAME = "Jarvis AI.cmd"


def _config_field_names() -> set[str]:
    return {field.name for field in fields(JarvisConfig)}


def _build_config(config_overrides: dict[str, Any] | None) -> JarvisConfig:
    """Load current config and merge installer overrides."""
    config = JarvisConfig.load()
    valid_fields = _config_field_names()
    for key, value in (config_overrides or {}).items():
        if key not in valid_fields:
            continue
        setattr(config, key, value)
    return config


def _preferred_windows_python() -> str:
    """Prefer pythonw.exe from the active venv on Windows."""
    if sys.platform == "win32":
        venv_dir = os.environ.get("VIRTUAL_ENV")
        if venv_dir:
            pythonw = Path(venv_dir) / "Scripts" / "pythonw.exe"
            if pythonw.exists():
                return str(pythonw)
    return sys.executable


def _jarvis_command(python_executable: str) -> list[str]:
    return [python_executable, "-m", "jarvis", "start", "--headless"]


def _cmd_line(command: list[str]) -> str:
    return subprocess.list2cmdline(command)


def _sh_cmd_line(command: list[str]) -> str:
    return shlex.join(command)


def _write_windows_startup_script(command: list[str], name: str = WINDOWS_STARTUP_NAME) -> Path:
    startup_dir = Path(os.environ.get("APPDATA", "")) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"
    startup_dir.mkdir(parents=True, exist_ok=True)
    script_path = startup_dir / name
    command_line = _cmd_line(command)
    script_path.write_text(
        "@echo off\r\n"
        "REM Jarvis auto-start generated by the installer\r\n"
        f"start \"\" {command_line}\r\n",
        encoding="utf-8",
    )
    return script_path


def _install_macos(command: list[str]) -> None:
    plist_path = Path("~/Library/LaunchAgents").expanduser() / f"{PLIST_LABEL}.plist"
    plist_path.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "Label": PLIST_LABEL,
        "ProgramArguments": command,
        "RunAtLoad": True,
        "KeepAlive": True,
        "StandardOutPath": str(Path("~/.jarvis/logs").expanduser() / "jarvis.log"),
        "StandardErrorPath": str(Path("~/.jarvis/logs").expanduser() / "jarvis_error.log"),
    }
    with plist_path.open("wb") as handle:
        plistlib.dump(payload, handle)

    subprocess.run(["launchctl", "load", str(plist_path)], check=False)
    print(f"Installed launchd plist: {plist_path}")


def _install_windows(command: list[str]) -> None:
    task_cmd = _cmd_line(command)
    result = subprocess.run(
        [
            "schtasks",
            "/create",
            "/tn",
            WINDOWS_TASK_NAME,
            "/tr",
            task_cmd,
            "/sc",
            "onlogon",
            "/f",
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode == 0:
        print("Installed Windows Task Scheduler entry.")
        return

    script_path = _write_windows_startup_script(command)
    print("Task Scheduler failed; wrote startup script instead.")
    print(f"Startup script: {script_path}")


def _install_linux(command: list[str]) -> None:
    unit_dir = Path("~/.config/systemd/user").expanduser()
    unit_dir.mkdir(parents=True, exist_ok=True)
    unit_path = unit_dir / "jarvis.service"
    exec_line = _sh_cmd_line(command)
    unit_path.write_text(
        "[Unit]\n"
        "Description=Jarvis AI Desktop Assistant\n"
        "After=graphical-session.target\n\n"
        "[Service]\n"
        "Type=simple\n"
        f"ExecStart={exec_line}\n"
        "Restart=on-failure\n"
        "RestartSec=5\n"
        "Environment=DISPLAY=:0\n\n"
        "[Install]\n"
        "WantedBy=default.target\n",
        encoding="utf-8",
    )

    subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
    subprocess.run(["systemctl", "--user", "enable", "jarvis"], check=False)
    subprocess.run(["systemctl", "--user", "start", "jarvis"], check=False)
    print(f"Installed systemd user service: {unit_path}")


def install(
    config_overrides: dict[str, Any] | None = None,
    *,
    enable_autostart: bool = True,
) -> JarvisConfig:
    """Install Jarvis auto-start for the current platform.

    The installer writes the shared Jarvis config, including startup defaults
    for the first launch sequence.
    """
    system = platform.system()
    config = _build_config(config_overrides)
    config.ensure_dirs()
    config.save()
    config.save_env()

    print(f"Saved config: {Path(config.jarvis_home).expanduser() / 'config.yaml'}")
    print(f"Saved secrets: {Path(config.jarvis_home).expanduser() / '.env'}")

    if not enable_autostart:
        print("Auto-start skipped.")
        return config

    command = _jarvis_command(_preferred_windows_python())

    if system == "Darwin":
        _install_macos(command)
    elif system == "Windows":
        _install_windows(command)
    elif system == "Linux":
        _install_linux(command)
    else:
        print(f"Unsupported platform: {system}")
        print("You can still run Jarvis manually: jarvis start")

    return config


def uninstall() -> None:
    """Remove Jarvis auto-start."""
    system = platform.system()
    if system == "Darwin":
        plist_path = Path("~/Library/LaunchAgents").expanduser() / f"{PLIST_LABEL}.plist"
        if plist_path.exists():
            subprocess.run(["launchctl", "unload", str(plist_path)], check=False)
            plist_path.unlink(missing_ok=True)
            print("Removed launchd plist.")
        else:
            print("Jarvis auto-start is not installed.")
    elif system == "Windows":
        subprocess.run(
            ["schtasks", "/delete", "/tn", WINDOWS_TASK_NAME, "/f"],
            capture_output=True,
            text=True,
        )
        startup_dir = Path(os.environ.get("APPDATA", "")) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"
        startup_script = startup_dir / WINDOWS_STARTUP_NAME
        startup_script.unlink(missing_ok=True)
        print("Removed Windows auto-start entries if present.")
    elif system == "Linux":
        subprocess.run(["systemctl", "--user", "stop", "jarvis"], check=False)
        subprocess.run(["systemctl", "--user", "disable", "jarvis"], check=False)
        unit_path = Path("~/.config/systemd/user/jarvis.service").expanduser()
        unit_path.unlink(missing_ok=True)
        print("Removed systemd user service.")
    else:
        print(f"Unsupported platform: {system}")
